org: makkifarah1992
app: apollo-lambda-app
# serverless.yml

service: apollo-lambda
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'eu-central-1'}
deploymentBucket:
  name: com.serverless.graphql.server.deploys
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
